package godep

const (
    WORLD_SIZE = 200
    INIT_CELL_ENERGY = 800
    INTERNAL_MEMORY_CAPACITY = 8
    LOGLEVEL = 3

    ENERGY_COST_INTERNAL = 5
    ENERGY_COST_SENSOR = 2
    ENERGY_COST_MODIFICATOR = 50
    ENERGY_COST_FAIL = 1000

// normal copies/mutated copies
// less mean more mutations level
    MUTATIONS_LEVEL_INSERT = 50
    MUTATIONS_LEVEL_DELETE = 10
    MUTATIONS_LEVEL = 200

    MUTATIONS_LEVEL_CONSTANT = 50
    MUTATIONS_CONSTANT_MAXD = 10

    MUTATIONS_LEVEL_DIRECTION = 50
)

